<?php

/**
 * @file
 * Example module to show uses for the Flag and Rules modules.
 */

include_once('gizra_access.features.inc');

/**
 * Implementation of hook_ca_predicate().
 *
 * Use @code print var_export(ca_load_predicate(1)); @endcode
 * to export an existing predicate.
 */
function gizra_access_ca_predicate() {
  $predicates = array();

  $predicates['show_content'] = array(
    '#title' => 'Show content and log purchase',
    '#description' => '',
    '#class' => '',
    '#status' => '1',
    '#weight' => '0',
    '#uid' => '0',
    '#trigger' => 'uc_order_status_update',
    '#conditions' =>
    array (
      '#operator' => 'AND',
      '#conditions' =>
      array (
        0 =>
        array (
          '#operator' => 'AND',
          '#conditions' =>
          array (
            0 =>
            array (
              '#name' => 'uc_order_status_condition',
              '#title' => 'Check the order status',
              '#argument_map' =>
              array (
                'order' => 'updated_order',
              ),
              '#settings' =>
              array (
                'negate' => 0,
                'order_status' => 'payment_received',
              ),
            ),
          ),
        ),
      ),
    ),
    '#actions' =>
    array (
      0 =>
      array (
        '#name' => 'ca_action_custom_php',
        '#title' => 'Execute custom PHP code',
        '#argument_map' =>
        array (
          'arguments' => 'arguments',
        ),
        '#settings' =>
        array (
          'php' => '_gizra_access_invoke_rule_set($updated_order);',
        ),
      ),
    ),

  );

  return $predicates;
}


/**
 * Implementation of hook_field_access().
 */
function gizra_access_field_access($op, $field, $account, $node) {
  if ($field['field_name'] == 'field_hidden_field' && $op == 'view' && $account->uid != 1) {
    // Check the user has a flagging on the content.
    $flag = flag_get_flag('show_content');
    return $flag->is_flagged($node->nid, $account->uid);
  }
}

/**
 * Add purchased products to user's content profile.
 *
 * @param $product_node
 *   Product node object.
 * @param $profile_node
 *   The user object of the buying user.
 * @return
 *   The node IDs that should be written to the field.
 */
function _gizra_access_add_purchased_products($product_node, $profile_node) {
  $nids = !empty($profile_node->field_purchased_products) ? $profile_node->field_purchased_products : array();
  // Add the user.
  $nids[] = array('nid' => $product_node->nid);

  return $nids;
}

/**
 * Invoke the "Show content" rule set when product has been purchased.
 *
 * @param $order
 *   The order object.
 */
function _gizra_access_invoke_rule_set($order) {
  $account = user_load($order->uid);
  // Go over all the products in the order.
  foreach ($order->products as $product) {
    $node = node_load($product->nid);
    rules_invoke_rule_set('rules_show_content', $node, $account);
  }
}